<?php

/**
 * Questa funzione invia nell'HEADER della response lo status e lo statusText
 * @param $num
 * @return void lancia la funzione header per scrivere nell'HEADER della response i seguenti valori:
 * 100 = 'HTTP/1.1 100 Continue'<br />
 * 101 = 'HTTP/1.1 101 Switching Protocols'<br />
 * 200 = 'HTTP/1.1 200 OK'<br />
 * 201 = 'HTTP/1.1 201 Created'<br />
 * 202 = 'HTTP/1.1 202 Accepted'<br />
 * 203 = 'HTTP/1.1 203 Non-Authoritative Information<br />
 * 204 = 'HTTP/1.1 204 No Content'<br />
 * 205 = 'HTTP/1.1 205 Reset Content'<br />
 * 206 = 'HTTP/1.1 206 Partial Content'<br />
 * 300 = 'HTTP/1.1 300 Multiple Choices'<br />
 * 301 = 'HTTP/1.1 301 Moved Permanently'<br />
 * 302 = 'HTTP/1.1 302 Found'<br />
 * 303 = 'HTTP/1.1 303 See Other'<br />
 * 304 = 'HTTP/1.1 304 Not Modified'<br />
 * 305 = 'HTTP/1.1 305 Use Proxy'<br />
 * 307 = 'HTTP/1.1 307 Temporary Redirect'<br />
 * 400 = 'HTTP/1.1 400 Bad Request'<br />
 * 401 = 'HTTP/1.1 401 Unauthorized'<br />
 * 402 = 'HTTP/1.1 402 Payment Required'<br />
 * 403 = 'HTTP/1.1 403 Forbidden'<br />
 * 404 = 'HTTP/1.1 404 Not Found'<br />
 * 405 = 'HTTP/1.1 405 Method Not Allowed'<br />
 * 406 = 'HTTP/1.1 406 Not Acceptable'<br />
 * 407 = 'HTTP/1.1 407 Proxy Authentication Required<br />
 * 408 = 'HTTP/1.1 408 Request Time-out'<br />
 * 409 = 'HTTP/1.1 409 Conflict'<br />
 * 410 = 'HTTP/1.1 410 Gone'<br />
 * 411 = 'HTTP/1.1 411 Length Required'<br />
 * 412 = 'HTTP/1.1 412 Precondition Failed'<br />
 * 413 = 'HTTP/1.1 413 Request Entity Too Large'<br />
 * 414 = 'HTTP/1.1 414 Request-URI Too Large'<br />
 * 415 = 'HTTP/1.1 415 Unsupported Media Type'<br />
 * 416 = 'HTTP/1.1 416 Requested Range Not Satisfiab<br />
 * 417 = 'HTTP/1.1 417 Expectation Failed'<br />
 * 500 = 'HTTP/1.1 500 Internal Server Error'<br />
 * 501 = 'HTTP/1.1 501 Not Implemented'<br />
 * 502 = 'HTTP/1.1 502 Bad Gateway'<br />
 * 503 = 'HTTP/1.1 503 Service Unavailable'<br />
 * 504 = 'HTTP/1.1 504 Gateway Time-out'<br />
 * 505 = 'HTTP/1.1 505 HTTP Version Not Supported'<br />
 */
function HTTPStatus($num) {

    $http = array(
        100 => 'HTTP/1.1 100 Continue',
        101 => 'HTTP/1.1 101 Switching Protocols',
        200 => 'HTTP/1.1 200 OK',
        201 => 'HTTP/1.1 201 Created',
        202 => 'HTTP/1.1 202 Accepted',
        203 => 'HTTP/1.1 203 Non-Authoritative Information',
        204 => 'HTTP/1.1 204 No Content',
        205 => 'HTTP/1.1 205 Reset Content',
        206 => 'HTTP/1.1 206 Partial Content',
        300 => 'HTTP/1.1 300 Multiple Choices',
        301 => 'HTTP/1.1 301 Moved Permanently',
        302 => 'HTTP/1.1 302 Found',
        303 => 'HTTP/1.1 303 See Other',
        304 => 'HTTP/1.1 304 Not Modified',
        305 => 'HTTP/1.1 305 Use Proxy',
        307 => 'HTTP/1.1 307 Temporary Redirect',
        400 => 'HTTP/1.1 400 Bad Request',
        401 => 'HTTP/1.1 401 Unauthorized',
        402 => 'HTTP/1.1 402 Payment Required',
        403 => 'HTTP/1.1 403 Forbidden',
        404 => 'HTTP/1.1 404 Not Found',
        405 => 'HTTP/1.1 405 Method Not Allowed',
        406 => 'HTTP/1.1 406 Not Acceptable',
        407 => 'HTTP/1.1 407 Proxy Authentication Required',
        408 => 'HTTP/1.1 408 Request Time-out',
        409 => 'HTTP/1.1 409 Conflict',
        410 => 'HTTP/1.1 410 Gone',
        411 => 'HTTP/1.1 411 Length Required',
        412 => 'HTTP/1.1 412 Precondition Failed',
        413 => 'HTTP/1.1 413 Request Entity Too Large',
        414 => 'HTTP/1.1 414 Request-URI Too Large',
        415 => 'HTTP/1.1 415 Unsupported Media Type',
        416 => 'HTTP/1.1 416 Requested Range Not Satisfiable',
        417 => 'HTTP/1.1 417 Expectation Failed',
        500 => 'HTTP/1.1 500 Internal Server Error',
        501 => 'HTTP/1.1 501 Not Implemented',
        502 => 'HTTP/1.1 502 Bad Gateway',
        503 => 'HTTP/1.1 503 Service Unavailable',
        504 => 'HTTP/1.1 504 Gateway Time-out',
        505 => 'HTTP/1.1 505 HTTP Version Not Supported',
    );

    header($http[$num]);

}

/**
 * Questa funzione invia nell'HEADER della request o della response il valore del Content-Type
 * @param $file_type
 * @return void lancia la funzione header per scrivere nell'HEADER della response i seguenti valori:
 * 'text_iso'  ='Content-Type: text/html; charset=iso-8859-1'<br />
 * 'text_utf8' ='Content-Type: text/html; charset=utf-8'<br />
 * 'xl'        ='Content-Type: application/excel'<br />
 * 'js'        ='Content-Type: application/javascript'<br />
 * 'hqx'       ='Content-Type: application/mac-binhex40'<br />
 * 'cpt'       ='Content-Type: application/mac-compactpro'<br />
 * 'bin'       ='Content-Type: application/macbinary'<br />
 * 'doc'       ='Content-Type: application/msword'<br />
 * 'word'      ='Content-Type: application/msword'<br />
 * 'xlsx'      ='Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'<br />
 * 'xltx'      ='Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.template'<br />
 * 'potx'      ='Content-Type: application/vnd.openxmlformats-officedocument.presentationml.template'<br />
 * 'ppsx'      ='Content-Type: application/vnd.openxmlformats-officedocument.presentationml.slideshow'<br />
 * 'pptx'      ='Content-Type: application/vnd.openxmlformats-officedocument.presentationml.presentation'<br />
 * 'sldx'      ='Content-Type: application/vnd.openxmlformats-officedocument.presentationml.slide'<br />
 * 'docx'      ='Content-Type: application/vnd.openxmlformats-officedocument.wordprocessingml.document'<br />
 * 'dotx'      ='Content-Type: application/vnd.openxmlformats-officedocument.wordprocessingml.template'<br />
 * 'xlam'      ='Content-Type: application/vnd.ms-excel.addin.macroEnabled.12'<br />
 * 'xlsb'      ='Content-Type: application/vnd.ms-excel.sheet.binary.macroEnabled.12'<br />
 * 'class'     ='Content-Type: application/octet-stream'<br />
 * 'dll'       ='Content-Type: application/octet-stream'<br />
 * 'dms'       ='Content-Type: application/octet-stream'<br />
 * 'exe'       ='Content-Type: application/octet-stream'<br />
 * 'lha'       ='Content-Type: application/octet-stream'<br />
 * 'lzh'       ='Content-Type: application/octet-stream'<br />
 * 'psd'       ='Content-Type: application/octet-stream'<br />
 * 'sea'       ='Content-Type: application/octet-stream'<br />
 * 'so'        ='Content-Type: application/octet-stream'<br />
 * 'oda'       ='Content-Type: application/oda'<br />
 * 'pdf'       ='Content-Type: application/pdf'<br />
 * 'ai'        ='Content-Type: application/postscript'<br />
 * 'eps'       ='Content-Type: application/postscript'<br />
 * 'ps'        ='Content-Type: application/postscript'<br />
 * 'smi'       ='Content-Type: application/smil'<br />
 * 'smil'      ='Content-Type: application/smil'<br />
 * 'mif'       ='Content-Type: application/vnd.mif'<br />
 * 'xls'       ='Content-Type: application/vnd.ms-excel'<br />
 * 'ppt'       ='Content-Type: application/vnd.ms-powerpoint'<br />
 * 'wbxml'     ='Content-Type: application/vnd.wap.wbxml'<br />
 * 'wmlc'      ='Content-Type: application/vnd.wap.wmlc'<br />
 * 'dcr'       ='Content-Type: application/x-director'<br />
 * 'dir'       ='Content-Type: application/x-director'<br />
 * 'dxr'       ='Content-Type: application/x-director'<br />
 * 'dvi'       ='Content-Type: application/x-dvi'<br />
 * 'gtar'      ='Content-Type: application/x-gtar'<br />
 * 'php3'      ='Content-Type: application/x-httpd-php'<br />
 * 'php4'      ='Content-Type: application/x-httpd-php'<br />
 * 'php'       ='Content-Type: application/x-httpd-php'<br />
 * 'phtml'     ='Content-Type: application/x-httpd-php'<br />
 * 'phps'      ='Content-Type: application/x-httpd-php-source'<br />
 * 'swf'       ='Content-Type: application/x-shockwave-flash'<br />
 * 'sit'       ='Content-Type: application/x-stuffit'<br />
 * 'tar'       ='Content-Type: application/x-tar'<br />
 * 'tgz'       ='Content-Type: application/x-tar'<br />
 * 'xht'       ='Content-Type: application/xhtml+xml'<br />
 * 'xhtml'     ='Content-Type: application/xhtml+xml'<br />
 * 'zip'       ='Content-Type: application/zip'<br />
 * 'mid'       ='Content-Type: audio/midi'<br />
 * 'midi'      ='Content-Type: audio/midi'<br />
 * 'mp2'       ='Content-Type: audio/mpeg'<br />
 * 'mp3'       ='Content-Type: audio/mpeg'<br />
 * 'm4a'       ='Content-Type: audio/mp4'<br />
 * 'mpga'      ='Content-Type: audio/mpeg'<br />
 * 'aif'       ='Content-Type: audio/x-aiff'<br />
 * 'aifc'      ='Content-Type: audio/x-aiff'<br />
 * 'aiff'      ='Content-Type: audio/x-aiff'<br />
 * 'ram'       ='Content-Type: audio/x-pn-realaudio'<br />
 * 'rm'        ='Content-Type: audio/x-pn-realaudio'<br />
 * 'rpm'       ='Content-Type: audio/x-pn-realaudio-plugin'<br />
 * 'ra'        ='Content-Type: audio/x-realaudio'<br />
 * 'wav'       ='Content-Type: audio/x-wav'<br />
 * 'mka'       ='Content-Type: audio/x-matroska'<br />
 * 'bmp'       ='Content-Type: image/bmp'<br />
 * 'gif'       ='Content-Type: image/gif'<br />
 * 'jpeg'      ='Content-Type: image/jpeg'<br />
 * 'jpe'       ='Content-Type: image/jpeg'<br />
 * 'jpg'       ='Content-Type: image/jpeg'<br />
 * 'png'       ='Content-Type: image/png'<br />
 * 'tiff'      ='Content-Type: image/tiff'<br />
 * 'tif'       ='Content-Type: image/tiff'<br />
 * 'webp'      ='Content-Type: image/webp'<br />
 * 'heif'      ='Content-Type: image/heif'<br />
 * 'heifs'     ='Content-Type: image/heif-sequence'<br />
 * 'heic'      ='Content-Type: image/heic'<br />
 * 'heics'     ='Content-Type: image/heic-sequence'<br />
 * 'eml'       ='Content-Type: message/rfc822'<br />
 * 'css'       ='Content-Type: text/css'<br />
 * 'html'      ='Content-Type: text/html'<br />
 * 'htm'       ='Content-Type: text/html'<br />
 * 'shtml'     ='Content-Type: text/html'<br />
 * 'log'       ='Content-Type: text/plain'<br />
 * 'text'      ='Content-Type: text/plain'<br />
 * 'rtx'       ='Content-Type: text/richtext'<br />
 * 'rtf'       ='Content-Type: text/rtf'<br />
 * 'vcf'       ='Content-Type: text/vcard'<br />
 * 'vcard'     ='Content-Type: text/vcard'<br />
 * 'ics'       ='Content-Type: text/calendar'<br />
 * 'xml'       ='Content-Type: text/xml'<br />
 * 'xsl'       ='Content-Type: text/xml'<br />
 * 'wmv'       ='Content-Type: video/x-ms-wmv'<br />
 * 'mpeg'      ='Content-Type: video/mpeg'<br />
 * 'mpe'       ='Content-Type: video/mpeg'<br />
 * 'mpg'       ='Content-Type: video/mpeg'<br />
 * 'mp4'       ='Content-Type: video/mp4'<br />
 * 'm4v'       ='Content-Type: video/mp4'<br />
 * 'mov'       ='Content-Type: video/quicktime'<br />
 * 'qt'        ='Content-Type: video/quicktime'<br />
 * 'rv'        ='Content-Type: video/vnd.rn-realvideo'<br />
 * 'avi'       ='Content-Type: video/x-msvideo'<br />
 * 'movie'     ='Content-Type: video/x-sgi-movie'<br />
 * 'webm'      ='Content-Type: video/webm'<br />
 * 'mkv'       ='Content-Type: video/x-matroska'<br />
 * 'json'      ='Content-Type: application/jsons'
 */
function HTTPContentType($file_type){

    $http = array(
        'text_iso'  => 'Content-Type: text/html; charset=iso-8859-1',
        'text_utf8' => 'Content-Type: text/html; charset=utf-8',
        'xl'        => 'Content-Type: application/excel',
        'js'        => 'Content-Type: application/javascript',
        'hqx'       => 'Content-Type: application/mac-binhex40',
        'cpt'       => 'Content-Type: application/mac-compactpro',
        'bin'       => 'Content-Type: application/macbinary',
        'doc'       => 'Content-Type: application/msword',
        'word'      => 'Content-Type: application/msword',
        'xlsx'      => 'Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        'xltx'      => 'Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.template',
        'potx'      => 'Content-Type: application/vnd.openxmlformats-officedocument.presentationml.template',
        'ppsx'      => 'Content-Type: application/vnd.openxmlformats-officedocument.presentationml.slideshow',
        'pptx'      => 'Content-Type: application/vnd.openxmlformats-officedocument.presentationml.presentation',
        'sldx'      => 'Content-Type: application/vnd.openxmlformats-officedocument.presentationml.slide',
        'docx'      => 'Content-Type: application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'dotx'      => 'Content-Type: application/vnd.openxmlformats-officedocument.wordprocessingml.template',
        'xlam'      => 'Content-Type: application/vnd.ms-excel.addin.macroEnabled.12',
        'xlsb'      => 'Content-Type: application/vnd.ms-excel.sheet.binary.macroEnabled.12',
        'class'     => 'Content-Type: application/octet-stream',
        'dll'       => 'Content-Type: application/octet-stream',
        'dms'       => 'Content-Type: application/octet-stream',
        'exe'       => 'Content-Type: application/octet-stream',
        'lha'       => 'Content-Type: application/octet-stream',
        'lzh'       => 'Content-Type: application/octet-stream',
        'psd'       => 'Content-Type: application/octet-stream',
        'sea'       => 'Content-Type: application/octet-stream',
        'so'        => 'Content-Type: application/octet-stream',
        'oda'       => 'Content-Type: application/oda',
        'pdf'       => 'Content-Type: application/pdf',
        'ai'        => 'Content-Type: application/postscript',
        'eps'       => 'Content-Type: application/postscript',
        'ps'        => 'Content-Type: application/postscript',
        'smi'       => 'Content-Type: application/smil',
        'smil'      => 'Content-Type: application/smil',
        'mif'       => 'Content-Type: application/vnd.mif',
        'xls'       => 'Content-Type: application/vnd.ms-excel',
        'ppt'       => 'Content-Type: application/vnd.ms-powerpoint',
        'wbxml'     => 'Content-Type: application/vnd.wap.wbxml',
        'wmlc'      => 'Content-Type: application/vnd.wap.wmlc',
        'dcr'       => 'Content-Type: application/x-director',
        'dir'       => 'Content-Type: application/x-director',
        'dxr'       => 'Content-Type: application/x-director',
        'dvi'       => 'Content-Type: application/x-dvi',
        'gtar'      => 'Content-Type: application/x-gtar',
        'php3'      => 'Content-Type: application/x-httpd-php',
        'php4'      => 'Content-Type: application/x-httpd-php',
        'php'       => 'Content-Type: application/x-httpd-php',
        'phtml'     => 'Content-Type: application/x-httpd-php',
        'phps'      => 'Content-Type: application/x-httpd-php-source',
        'swf'       => 'Content-Type: application/x-shockwave-flash',
        'sit'       => 'Content-Type: application/x-stuffit',
        'tar'       => 'Content-Type: application/x-tar',
        'tgz'       => 'Content-Type: application/x-tar',
        'xht'       => 'Content-Type: application/xhtml+xml',
        'xhtml'     => 'Content-Type: application/xhtml+xml',
        'zip'       => 'Content-Type: application/zip',
        'mid'       => 'Content-Type: audio/midi',
        'midi'      => 'Content-Type: audio/midi',
        'mp2'       => 'Content-Type: audio/mpeg',
        'mp3'       => 'Content-Type: audio/mpeg',
        'm4a'       => 'Content-Type: audio/mp4',
        'mpga'      => 'Content-Type: audio/mpeg',
        'aif'       => 'Content-Type: audio/x-aiff',
        'aifc'      => 'Content-Type: audio/x-aiff',
        'aiff'      => 'Content-Type: audio/x-aiff',
        'ram'       => 'Content-Type: audio/x-pn-realaudio',
        'rm'        => 'Content-Type: audio/x-pn-realaudio',
        'rpm'       => 'Content-Type: audio/x-pn-realaudio-plugin',
        'ra'        => 'Content-Type: audio/x-realaudio',
        'wav'       => 'Content-Type: audio/x-wav',
        'mka'       => 'Content-Type: audio/x-matroska',
        'bmp'       => 'Content-Type: image/bmp',
        'gif'       => 'Content-Type: image/gif',
        'jpeg'      => 'Content-Type: image/jpeg',
        'jpe'       => 'Content-Type: image/jpeg',
        'jpg'       => 'Content-Type: image/jpeg',
        'png'       => 'Content-Type: image/png',
        'tiff'      => 'Content-Type: image/tiff',
        'tif'       => 'Content-Type: image/tiff',
        'webp'      => 'Content-Type: image/webp',
        'heif'      => 'Content-Type: image/heif',
        'heifs'     => 'Content-Type: image/heif-sequence',
        'heic'      => 'Content-Type: image/heic',
        'heics'     => 'Content-Type: image/heic-sequence',
        'eml'       => 'Content-Type: message/rfc822',
        'css'       => 'Content-Type: text/css',
        'html'      => 'Content-Type: text/html',
        'htm'       => 'Content-Type: text/html',
        'shtml'     => 'Content-Type: text/html',
        'log'       => 'Content-Type: text/plain',
        'text'      => 'Content-Type: text/plain',
        'rtx'       => 'Content-Type: text/richtext',
        'rtf'       => 'Content-Type: text/rtf',
        'vcf'       => 'Content-Type: text/vcard',
        'vcard'     => 'Content-Type: text/vcard',
        'ics'       => 'Content-Type: text/calendar',
        'xml'       => 'Content-Type: text/xml',
        'xsl'       => 'Content-Type: text/xml',
        'wmv'       => 'Content-Type: video/x-ms-wmv',
        'mpeg'      => 'Content-Type: video/mpeg',
        'mpe'       => 'Content-Type: video/mpeg',
        'mpg'       => 'Content-Type: video/mpeg',
        'mp4'       => 'Content-Type: video/mp4',
        'm4v'       => 'Content-Type: video/mp4',
        'mov'       => 'Content-Type: video/quicktime',
        'qt'        => 'Content-Type: video/quicktime',
        'rv'        => 'Content-Type: video/vnd.rn-realvideo',
        'avi'       => 'Content-Type: video/x-msvideo',
        'movie'     => 'Content-Type: video/x-sgi-movie',
        'webm'      => 'Content-Type: video/webm',
        'mkv'       => 'Content-Type: video/x-matroska',
        'json'      => 'Content-Type: application/jsons');

    header($http[$file_type]);

}
